### PR TITLE
Clean-up of collateral files/directories

### PR DESCRIPTION
**Pull request by rbergen**
This PR adds a .gitignore and removes .vs and obj subdirectories from PlummersSoftwareLLC/Primes#489.

### CODE REVIEW

**Comment by davepl** [comment]
Thanks for cleaning up my mess :-)

**Comment by rbergen** [comment]
No problem, I went through the same thing about 18 months ago. Don't forget to merge it though ;)

**Comment by ItalyToast** [comment]
I ran into a missing .gitignore when messing with the other solutions aswell, maybe you could have the .gitignore in the PrimeCSharp folder or add it to the other solutions aswell?

**Comment by ItalyToast** [comment]
I made a pr for a common C# .gitignore here: #512

**Comment by rbergen** [comment]
> I made a pr for a common C# .gitignore here: [PlummersSoftwareLLC#512](https://github.com/PlummersSoftwareLLC/Primes/pull/512)

I appreciate your intention to help out with this, but we won't merge cross-language, multi-solution files. It is up to the author of each individual solution to determine what they want to .gitignore or not. If you want to apply a .gitignore to all C# solutions then you can open a PR that adds one to each C# solution that doesn't already have one (where you can skip solution_2, because this PR will arrange that one). We will then ask the authors of those solutions to indicate if they want to adopt it or not. 

Based on the previous, I will close PlummersSoftwareLLC#512.

**Comment by davepl** [comment]
Thanks!

**Pull request merged**
